#!/usr/bin/env bash

set -e

os_type=$(uname -s);

if [[ $os_type == 'Linux' ]]; then
    URL=https://github.com/gohugoio/hugo/releases/download/v0.137.1/hugo_0.137.1_linux-amd64.tar.gz
elif [[ $os_type == 'Darwin' ]]; then
    URL=https://github.com/gohugoio/hugo/releases/download/v0.137.1/hugo_0.137.1_darwin-universal.tar.gz
else echo 'ARCHITETTURA NON RICONOSCIUTA';
fi

if ! [[ -f "./bin/hugo" ]]; then
    echo "Hugo binary missing, downloading..."
    mkdir -p bin
    cd bin && wget -c $URL -O - | tar -xz
    cd -
fi

chmod +x ./bin/hugo

./bin/hugo "$@"
