#!/usr/bin/env bash

os_type=`uname -s`;

if [[ $os_type == 'Linux' ]]; then
    ./bin/hugo_0.69.0_linux64 "$@"
elif [[ $os_type == 'Darwin' ]]; then
    ./bin/hugo_0.69.0_osx64 "$@"
else echo 'ARCHITETTURA NON RICONOSCIUTA';
fi
